#!/usr/bin/env python3
"""Render/check swap policies against approved, locally remeasured EIF artifacts.

This is an offline deployment gate, not an AWS policy mutation tool. Approval
must be an independently reviewed release record, never generated by this tool.
Requires trusted nitro-cli >=1.4.5 with describe-eif Docker metadata support.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys

TEMPLATES = Path(__file__).resolve().parent
POLICIES = ("swap-kms-key-policy.json", "swap-seed-bucket-policy.json", "swap-signer-role-policy.json")
PUBLIC_PINS = ("SWAP_KMS_KEY_ARN", "SWAP_KMS_REGION", "SWAP_KMS_SEED_ID", "SWAP_KMS_EXPECTED_EVM_ADDRESS")
LIVE_CHECKS = ("approved_bootstrap_and_restore", "restore_identity_after_restart", "missing_recipient_denied", "unapproved_pcr_denied", "debug_pcr_denied", "wrong_context_denied", "overwrite_and_delete_denied", "independent_backup_recovery")


class ValidationError(Exception):
    pass


def require(condition, message):
    if not condition:
        raise ValidationError(message)


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        require(key not in result, "duplicate JSON key")
        result[key] = value
    return result


def read_json(path):
    text = Path(path).read_text()
    require(len(text) <= 1024 * 1024, "JSON document exceeds 1 MiB")
    return json.loads(text, object_pairs_hook=unique_object)


def digest(path):
    result = hashlib.sha256()
    with Path(path).open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            result.update(chunk)
    return result.hexdigest()


def public_text(value):
    return isinstance(value, str) and 0 < len(value) <= 1024 and all(32 <= ord(c) <= 126 for c in value) and not re.search(r"REPLACE_|EXAMPLE|YOUR_|<|>", value, re.I)


def valid_hex(value, length):
    return isinstance(value, str) and re.fullmatch(r"[0-9a-fA-F]{%d}" % length, value) and len(set(value.lower())) > 2


def image_mode(image):
    """Identity protection follows the pin; there is no separate creation switch."""
    return "bootstrap" if image["expected_evm_address"] == "" else "restore"


def validate_approval(approval):
    expected = {"version", "phase", "approved_by", "approval_reference", "account_id", "signer_role", "key_admin_role", "key_arn", "region", "seed_id", "bitcoin_network", "bucket", "object_key", "images"}
    require(isinstance(approval, dict) and set(approval) == expected, "invalid approval fields")
    require(type(approval["version"]) is int and approval["version"] == 1, "unsupported approval version")
    require(approval["phase"] in ("bootstrap", "transition", "restore"), "invalid deployment phase")
    for name in expected - {"version", "images"}:
        require(public_text(approval[name]), "invalid or placeholder approval field: " + name)
    account = approval["account_id"]
    require(re.fullmatch(r"[0-9]{12}", account) and len(set(account)) > 1 and account not in ("123456789012", "111122223333"), "fixture or invalid AWS account")
    region = approval["region"]
    require(re.fullmatch(r"[a-z]{2}-[a-z]+-[0-9]+", region) and not region.startswith(("cn-", "us-gov-", "us-iso")), "invalid commercial AWS region")
    key_prefix = f"arn:aws:kms:{region}:{account}:key/"
    key_id = approval["key_arn"].removeprefix(key_prefix)
    require(approval["key_arn"].startswith(key_prefix) and re.fullmatch(r"(?:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|mrk-[0-9a-f]{32})", key_id), "KMS key must match approved account and region")
    require(valid_hex(key_id.removeprefix("mrk-").replace("-", ""), 32) and key_id != "12345678-1234-1234-1234-123456789012", "fixture KMS key")
    for name in ("signer_role", "key_admin_role"):
        require(re.fullmatch(r"[A-Za-z0-9+=,.@_/-]{1,512}", approval[name]) and not approval[name].startswith("/"), "invalid IAM role")
    require(approval["signer_role"] != approval["key_admin_role"], "signer and key administrator must be separate")
    require(re.fullmatch(r"[A-Za-z0-9._-]{1,128}", approval["seed_id"]), "invalid seed ID")
    require(not re.search(r"fixture|validation-only|local-e2e", approval["seed_id"], re.I), "fixture seed ID")
    require(approval["bitcoin_network"] in ("bitcoin", "testnet", "signet", "regtest"), "invalid Bitcoin network")
    require(re.fullmatch(r"[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]", approval["bucket"]), "invalid bucket")
    require(not any(c in approval["bucket"] + approval["object_key"] for c in "*?${}"), "wildcards and policy variables are forbidden in storage pins")
    images = approval["images"]
    require(isinstance(images, list) and 1 <= len(images) <= 8, "approve between one and eight images")
    modes, restore_addresses, seen = [], set(), set()
    for image in images:
        require(isinstance(image, dict) and set(image) == {"eif", "pcr_file", "sha256", "pcr0", "expected_evm_address"}, "invalid image approval fields")
        require(public_text(image["eif"]) and public_text(image["pcr_file"]), "invalid image paths")
        require(valid_hex(image["sha256"], 64) and valid_hex(image["pcr0"], 96), "fixture, debug-zero, or invalid image digest/PCR0")
        pcr = image["pcr0"].lower()
        require(pcr not in seen, "duplicate image PCR0")
        seen.add(pcr)
        modes.append(image_mode(image))
        address = image["expected_evm_address"]
        if image_mode(image) == "bootstrap":
            require(address == "", "bootstrap must not pin an unknown identity")
        else:
            require(isinstance(address, str) and address.startswith("0x") and valid_hex(address[2:], 40), "restore requires a non-fixture public identity")
            restore_addresses.add(address.lower())
    require(len(restore_addresses) <= 1, "restore images must pin the same identity")
    phase = approval["phase"]
    require((phase == "bootstrap" and modes == ["bootstrap"]) or (phase == "transition" and modes.count("bootstrap") == 1 and "restore" in modes) or (phase == "restore" and set(modes) == {"restore"}), "images do not match deployment lifecycle phase")


def describe_eif(path):
    completed = subprocess.run(["nitro-cli", "describe-eif", "--eif-path", str(path)], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=120)
    require(len(completed.stdout) <= 1024 * 1024, "describe-eif output exceeds 1 MiB")
    return json.loads(completed.stdout, object_pairs_hook=unique_object)


def verify_image(approval, image, directory, describe=describe_eif):
    path = (directory / image["eif"]).resolve()
    require(digest(path) == image["sha256"].lower(), "EIF differs from independently approved SHA256")
    info = describe(path)
    require(info.get("CheckCRC") is True, "EIF CRC verification failed or unavailable")
    require(info.get("EifVersion", 0) >= 4, "EIF metadata format unavailable")
    require(not info.get("IsSigned") or info.get("SignatureCheck") is True, "signed EIF verification failed")
    actual = info.get("Measurements", {})
    recorded = read_json(directory / image["pcr_file"])
    for pcr in ("PCR0", "PCR1", "PCR2"):
        require(valid_hex(actual.get(pcr), 96), "invalid/debug/fixture measured " + pcr)
        require(isinstance(recorded.get(pcr), str) and recorded[pcr].lower() == actual[pcr].lower(), "recorded PCR.json does not match actual EIF " + pcr)
    require(actual["PCR0"].lower() == image["pcr0"].lower(), "EIF PCR0 does not match independent approval")
    env_list = info.get("Metadata", {}).get("DockerInfo", {}).get("Config", {}).get("Env")
    require(isinstance(env_list, list), "actual EIF Docker environment metadata is required")
    env = {}
    for entry in env_list:
        require(isinstance(entry, str) and "=" in entry, "invalid EIF environment")
        name, value = entry.split("=", 1)
        require(name not in env, "duplicate EIF environment setting")
        env[name] = value
    require(not any(name.startswith("SWAP_KMS_") and name not in PUBLIC_PINS for name in env), "unexpected swap KMS setting in approved EIF")
    require(not any(name in env for name in ("AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN")), "static AWS credentials must not be embedded in an EIF")
    expected = dict(zip(PUBLIC_PINS, (approval["key_arn"], approval["region"], approval["seed_id"], image["expected_evm_address"])))
    expected["BITCOIN_NETWORK"] = approval["bitcoin_network"]
    require(all(env.get(name) == value for name, value in expected.items()), "EIF public custody configuration differs from approval")
    # Recheck after describe-eif to catch accidental replacement during review.
    require(digest(path) == image["sha256"].lower(), "EIF changed during validation")
    return {"sha256": image["sha256"].lower(), "pcr0": actual["PCR0"].lower(), "mode": image_mode(image)}


def rendered_policies(approval):
    pcrs = [image["pcr0"].lower() for image in approval["images"]]
    bootstrap = next((i["pcr0"].lower() for i in approval["images"] if image_mode(i) == "bootstrap"), pcrs[0])
    replacements = {
        "REPLACE_ACCOUNT_ID": approval["account_id"], "REPLACE_SIGNER_ROLE": approval["signer_role"],
        "REPLACE_KEY_ADMIN_ROLE": approval["key_admin_role"], "REPLACE_KMS_KEY_ARN": approval["key_arn"],
        "REPLACE_SEED_ID": approval["seed_id"], "REPLACE_BITCOIN_NETWORK": approval["bitcoin_network"],
        "REPLACE_SEED_BUCKET": approval["bucket"], "REPLACE_SEED_OBJECT_KEY": approval["object_key"],
        "REPLACE_BOOTSTRAP_PCR0": bootstrap, "REPLACE_RESTORE_PCR0": pcrs[-1],
    }

    def replace(value):
        if isinstance(value, str):
            for old, new in replacements.items():
                value = value.replace(old, new)
            return value
        if isinstance(value, list):
            return [replace(v) for v in value]
        if isinstance(value, dict):
            return {k: replace(v) for k, v in value.items()}
        return value

    policies = {name: replace(read_json(TEMPLATES / name)) for name in POLICIES}
    key = policies[POLICIES[0]]
    for statement in key["Statement"]:
        if statement["Sid"] == "AllowAttestedSeedRecovery":
            statement["Condition"]["StringEqualsIgnoreCase"]["kms:RecipientAttestation:PCR0"] = pcrs
        if statement["Sid"] == "DenyDecryptOutsideApprovedImages":
            statement["Condition"]["StringNotEqualsIgnoreCase"]["kms:RecipientAttestation:PCR0"] = pcrs
        if approval["phase"] == "restore" and statement["Sid"] == "DenyGenerateDataKeyOutsideBootstrapImage":
            statement["Sid"] = "DenySeedGenerationAfterBootstrap"
            del statement["Condition"]
    if approval["phase"] == "restore":
        key["Statement"] = [s for s in key["Statement"] if s["Sid"] != "AllowBootstrapGenerateDataKey"]
    require("REPLACE_" not in json.dumps(policies), "unresolved policy placeholder")
    return policies


def compare_policy(actual, expected):
    # Statement ordering/JSON whitespace are harmless; every semantic field and
    # condition must otherwise match. Additional allows/omitted denies fail closed.
    require(isinstance(actual, dict) and set(actual) == {"Version", "Statement"}, "invalid policy root")
    statements = actual["Statement"]
    require(isinstance(statements, list) and all(isinstance(s, dict) and isinstance(s.get("Sid"), str) for s in statements), "invalid policy statements")
    require(len({s["Sid"] for s in statements}) == len(statements), "duplicate policy statement")
    require(actual["Version"] == expected["Version"] and {s["Sid"]: s for s in statements} == {s["Sid"]: s for s in expected["Statement"]}, "policy differs from approved lifecycle, roles, context, or protection rules")


def validate_live_evidence(evidence, approval):
    require(isinstance(evidence, dict) and set(evidence) == {"approval_reference", "checks"}, "invalid live evidence fields")
    require(evidence["approval_reference"] == approval["approval_reference"], "live evidence must refer to this approved release")
    require(isinstance(evidence["checks"], dict) and set(evidence["checks"]) == set(LIVE_CHECKS), "missing mandatory AWS/Nitro validation evidence")
    for check in LIVE_CHECKS:
        record = evidence["checks"][check]
        require(isinstance(record, dict) and set(record) == {"passed", "evidence"} and record["passed"] is True and public_text(record["evidence"]), "live check failed or evidence missing: " + check)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--approval", type=Path, required=True)
    parser.add_argument("--policy-dir", type=Path, help="validate already rendered/downloaded policy files")
    parser.add_argument("--output-dir", type=Path, help="write reviewed policies and validation receipt (never applies to AWS)")
    parser.add_argument("--production-ready", action="store_true", help="require restore-only phase and mandatory live AWS/Nitro evidence")
    parser.add_argument("--live-evidence", type=Path)
    args = parser.parse_args()
    try:
        require(args.policy_dir is not None or args.output_dir is not None, "provide --policy-dir or --output-dir")
        approval = read_json(args.approval)
        validate_approval(approval)
        images = [verify_image(approval, image, args.approval.resolve().parent) for image in approval["images"]]
        policies = rendered_policies(approval)
        if args.policy_dir:
            for name, expected in policies.items():
                compare_policy(read_json(args.policy_dir / name), expected)
        if args.production_ready:
            require(args.policy_dir is not None, "production gate requires the applied policy documents")
            require(approval["phase"] == "restore", "production gate requires retired bootstrap authority")
            require(args.live_evidence is not None, "production gate requires live validation evidence")
            validate_live_evidence(read_json(args.live_evidence), approval)
        receipt = {"approval_sha256": digest(args.approval), "phase": approval["phase"], "images": images, "policy_sha256": {name: hashlib.sha256((json.dumps(value, indent=2) + "\n").encode()).hexdigest() for name, value in policies.items()}, "production_evidence_checked": args.production_ready}
        if args.output_dir:
            # Refuse to overwrite a previous policy release/receipt by accident.
            args.output_dir.mkdir(parents=True, exist_ok=False)
            for name, value in {**policies, "validation-receipt.json": receipt}.items():
                (args.output_dir / name).write_text(json.dumps(value, indent=2) + "\n")
        print(json.dumps(receipt, indent=2))
        return 0
    except ValidationError as error:
        print("Deployment validation failed: " + str(error), file=sys.stderr)
        return 1
    except (OSError, ValueError, KeyError, TypeError, subprocess.SubprocessError):
        # Inputs are public, but subprocess output could contain credentials.
        print("Deployment validation failed; check the approval, actual EIF artifacts, policies, and required evidence.", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
