// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnclaveRequest {
    #[prost(oneof="enclave_request::Request", tags="1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16")]
    pub request: ::core::option::Option<enclave_request::Request>,
}
/// Nested message and enum types in `EnclaveRequest`.
pub mod enclave_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Request {
        #[prost(message, tag="1")]
        InitializeKey(super::InitializeKeyRequest),
        #[prost(message, tag="2")]
        GetPublicKey(super::GetPublicKeyRequest),
        #[prost(message, tag="3")]
        Sign(super::SignRequest),
        #[prost(message, tag="5")]
        SignRawMessage(super::SignRawMessageRequest),
        #[prost(message, tag="6")]
        ProxyFederation(super::ProxyFederationRequest),
        #[prost(message, tag="7")]
        InitiateCloning(super::InitiateCloningRequest),
        #[prost(message, tag="8")]
        GetClone(super::GetCloneRequest),
        #[prost(message, tag="9")]
        SetClone(super::SetCloneRequest),
        #[prost(message, tag="10")]
        SignRawDigest(super::SignRawDigestRequest),
        #[prost(message, tag="11")]
        SubmitHeaders(super::SubmitHeadersRequest),
        #[prost(message, tag="12")]
        GetLastSavedBlock(super::GetLastSavedBlockRequest),
        #[prost(message, tag="13")]
        GetAttestedPublicKey(super::GetAttestedPublicKeyRequest),
        #[prost(message, tag="14")]
        SignBtc(super::SignBtcRequest),
        #[prost(message, tag="15")]
        SignCcd(super::SignCcdRequest),
        #[prost(message, tag="16")]
        Health(super::HealthRequest),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnclaveResponse {
    #[prost(oneof="enclave_response::Response", tags="1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16")]
    pub response: ::core::option::Option<enclave_response::Response>,
}
/// Nested message and enum types in `EnclaveResponse`.
pub mod enclave_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag="1")]
        InitializeKey(super::InitializeKeyResponse),
        #[prost(message, tag="2")]
        PublicKeys(super::PublicKeysResponse),
        #[prost(message, tag="3")]
        EvmSignature(super::EvmSignatureResponse),
        #[prost(message, tag="4")]
        SignedPsbt(super::SignedPsbtResponse),
        #[prost(message, tag="5")]
        RawSignature(super::RawSignatureResponse),
        #[prost(message, tag="6")]
        FederationSig(super::FederationSignatureResponse),
        #[prost(message, tag="7")]
        InitiateCloning(super::InitiateCloningResponse),
        #[prost(message, tag="8")]
        GetClone(super::GetCloneResponse),
        #[prost(message, tag="9")]
        SetClone(super::SetCloneResponse),
        #[prost(message, tag="10")]
        RawDigestSig(super::RawDigestSignatureResponse),
        #[prost(message, tag="11")]
        SubmitHeaders(super::SubmitHeadersResponse),
        #[prost(message, tag="12")]
        GetLastSavedBlock(super::GetLastSavedBlockResponse),
        #[prost(message, tag="13")]
        GetAttestedPublicKey(super::GetAttestedPublicKeyResponse),
        #[prost(message, tag="14")]
        CcdSignature(super::CcdSignatureResponse),
        #[prost(message, tag="15")]
        Error(super::ErrorResponse),
        #[prost(message, tag="16")]
        Health(super::HealthResponse),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InitializeKeyRequest {
    /// Empty seed and mnemonic generate a new mnemonic from enclave entropy.
    /// Non-empty = import raw 64-byte seed (requires `allow-seed-import` feature, testing only).
    #[prost(bytes="vec", tag="1")]
    pub seed: ::prost::alloc::vec::Vec<u8>,
    /// BIP-39 mnemonic phrase (requires `allow-seed-import` feature, testing only).
    /// If non-empty, takes precedence over seed.
    #[prost(string, tag="2")]
    pub mnemonic: ::prost::alloc::string::String,
    /// Donor-side cloning secret, delivered at runtime (NOT baked into the EIF, so
    /// it stays out of the PCRs). Optional: only set for enclaves that will serve
    /// GetClone. Empty = donor cloning disabled.
    #[prost(string, tag="3")]
    pub cloning_secret: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InitializeKeyResponse {
    /// 20 bytes: keccak256(uncompressed_pubkey\[1..\])[12..].
    #[prost(bytes="vec", tag="1")]
    pub evm_address: ::prost::alloc::vec::Vec<u8>,
    /// 33-byte compressed secp256k1 public key.
    #[prost(bytes="vec", tag="2")]
    pub btc_compressed_pub: ::prost::alloc::vec::Vec<u8>,
    /// Base58 BIP-32 extended public key.
    #[prost(string, tag="3")]
    pub btc_xpub: ::prost::alloc::string::String,
    /// 4-byte BIP-32 master key fingerprint.
    #[prost(bytes="vec", tag="4")]
    pub master_fingerprint: ::prost::alloc::vec::Vec<u8>,
    /// BIP-86 account xpub: m/86'/<coin>'/0'.
    #[prost(string, tag="5")]
    pub account_xpub_vanilla: ::prost::alloc::string::String,
    /// RGB BIP-86 account xpub: m/86'/827167'/0'.
    #[prost(string, tag="6")]
    pub account_xpub_colored: ::prost::alloc::string::String,
    /// 64-byte secp256k1 X || Y, without 0x04 prefix.
    #[prost(bytes="vec", tag="7")]
    pub evm_uncompressed_pub: ::prost::alloc::vec::Vec<u8>,
    /// EVM chain ID pinned at enclave boot.
    #[prost(uint64, tag="8")]
    pub chain_id: u64,
    /// 20-byte bridge contract address pinned at enclave boot.
    #[prost(bytes="vec", tag="9")]
    pub bridge_contract: ::prost::alloc::vec::Vec<u8>,
    /// RGB asset identifier pinned at enclave boot.
    #[prost(string, tag="10")]
    pub rgb_asset_id: ::prost::alloc::string::String,
    /// 64-byte gas transaction public key.
    #[prost(bytes="vec", tag="11")]
    pub evm_gas_tx_uncompressed_pub: ::prost::alloc::vec::Vec<u8>,
    /// 20-byte Ethereum address of the gas transaction key.
    #[prost(bytes="vec", tag="12")]
    pub evm_gas_tx_address: ::prost::alloc::vec::Vec<u8>,
    /// 32-byte Concordium Ed25519 governance public key.
    #[prost(bytes="vec", tag="13")]
    pub ccd_ed25519_pub: ::prost::alloc::vec::Vec<u8>,
}
/// Empty request returns the full public-key bundle.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPublicKeyRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PublicKeysResponse {
    /// 20-byte Ethereum address of the primary signing key.
    #[prost(bytes="vec", tag="1")]
    pub evm_address: ::prost::alloc::vec::Vec<u8>,
    /// 33-byte compressed Bitcoin public key.
    #[prost(bytes="vec", tag="2")]
    pub btc_compressed_pub: ::prost::alloc::vec::Vec<u8>,
    /// Base58 BIP-32 extended public key.
    #[prost(string, tag="3")]
    pub btc_xpub: ::prost::alloc::string::String,
    /// 4-byte BIP-32 master key fingerprint.
    #[prost(bytes="vec", tag="4")]
    pub master_fingerprint: ::prost::alloc::vec::Vec<u8>,
    /// BIP-86 account xpub: m/86'/<coin>'/0'.
    #[prost(string, tag="5")]
    pub account_xpub_vanilla: ::prost::alloc::string::String,
    /// RGB BIP-86 account xpub: m/86'/827167'/0'.
    #[prost(string, tag="6")]
    pub account_xpub_colored: ::prost::alloc::string::String,
    /// 64-byte secp256k1 X || Y, without 0x04 prefix.
    #[prost(bytes="vec", tag="7")]
    pub evm_uncompressed_pub: ::prost::alloc::vec::Vec<u8>,
    /// EVM chain ID pinned at enclave boot.
    #[prost(uint64, tag="8")]
    pub chain_id: u64,
    /// 20-byte bridge contract address pinned at enclave boot.
    #[prost(bytes="vec", tag="9")]
    pub bridge_contract: ::prost::alloc::vec::Vec<u8>,
    /// RGB asset identifier pinned at enclave boot.
    #[prost(string, tag="10")]
    pub rgb_asset_id: ::prost::alloc::string::String,
    /// 64-byte gas transaction public key.
    #[prost(bytes="vec", tag="11")]
    pub evm_gas_tx_uncompressed_pub: ::prost::alloc::vec::Vec<u8>,
    /// 20-byte Ethereum address of the gas transaction key.
    #[prost(bytes="vec", tag="12")]
    pub evm_gas_tx_address: ::prost::alloc::vec::Vec<u8>,
    /// 32-byte Concordium Ed25519 governance public key.
    #[prost(bytes="vec", tag="13")]
    pub ccd_ed25519_pub: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAttestedPublicKeyRequest {
    /// Fresh 32-byte nonce embedded in the attestation document.
    #[prost(bytes="vec", tag="1")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAttestedPublicKeyResponse {
    /// Public-key bundle bound by the attestation.
    #[prost(message, optional, tag="1")]
    pub public_keys: ::core::option::Option<PublicKeysResponse>,
    /// COSE_Sign1 NSM document, or raw CBOR in mock mode.
    #[prost(bytes="vec", tag="2")]
    pub attestation_doc: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignRequest {
    #[prost(uint64, tag="1")]
    pub amount: u64,
    #[prost(oneof="sign_request::SourceNetwork", tags="2, 3, 6")]
    pub source_network: ::core::option::Option<sign_request::SourceNetwork>,
    #[prost(oneof="sign_request::DestinationNetwork", tags="4, 5")]
    pub destination_network: ::core::option::Option<sign_request::DestinationNetwork>,
}
/// Nested message and enum types in `SignRequest`.
pub mod sign_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum SourceNetwork {
        #[prost(message, tag="2")]
        EvmSource(super::EvmSource),
        #[prost(message, tag="3")]
        RgbSource(super::RgbSource),
        #[prost(message, tag="6")]
        CcdSource(super::CcdSource),
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum DestinationNetwork {
        #[prost(message, tag="4")]
        EvmDestination(super::EvmDestination),
        #[prost(message, tag="5")]
        RgbDestination(super::RgbDestination),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EvmSource {
    /// 32-byte source EVM transaction hash.
    #[prost(bytes="vec", tag="1")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    /// Whether the listener validated the source EVM event.
    #[prost(bool, tag="2")]
    pub event_valid: bool,
    /// Whether the source EVM event is finalized.
    #[prost(bool, tag="3")]
    pub event_finalized: bool,
    /// 20-byte ERC-20 address; empty for native currency.
    #[prost(bytes="vec", tag="4")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    /// 20-byte recipient address.
    #[prost(bytes="vec", tag="5")]
    pub recipient: ::prost::alloc::vec::Vec<u8>,
    /// Commission reported by the source event.
    #[prost(uint64, tag="6")]
    pub commission: u64,
    /// On-chain BridgeFundsIn.operationId of the source deposit, exactly 32 bytes.
    /// Required: the enclave binds the FundsIn log to it and refuses to sign
    /// without it. Not RgbDestination.operation_idx, which is a different id-space.
    #[prost(bytes="vec", tag="7")]
    pub funds_in_operation_id: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RgbSource {
    /// Listener-provided RGB validation result.
    #[prost(bool, tag="1")]
    pub consignment_valid: bool,
    /// RGB asset identifier derived from the consignment.
    #[prost(string, tag="3")]
    pub asset_id: ::prost::alloc::string::String,
    /// Raw RGB consignment bytes.
    #[prost(bytes="vec", tag="4")]
    pub consignment: ::prost::alloc::vec::Vec<u8>,
    /// keccak256(consignment).
    #[prost(bytes="vec", tag="5")]
    pub consignment_hash: ::prost::alloc::vec::Vec<u8>,
    /// SPV proofs for witness transactions.
    #[prost(message, repeated, tag="6")]
    pub merkle_proofs: ::prost::alloc::vec::Vec<MerkleProofEntry>,
    /// Commission reported by the source event.
    #[prost(uint64, tag="7")]
    pub commission: u64,
    /// Every historical BFA mint the consignment descends from, paired with the
    /// EVM transaction that authorised it.
    ///
    /// A burn consignment necessarily carries its whole mint ancestry, and each
    /// of those mint transitions runs a script that demands a verified FundsIn
    /// event. The enclave cannot find those receipts on its own - unlike the mint
    /// direction, whose EvmSource already names its own tx_hash - so the listener
    /// supplies the pairs and the enclave verifies every one of them. A missing or
    /// mismatched entry fails the validation closed; these are hints, never
    /// evidence.
    #[prost(message, repeated, tag="8")]
    pub mint_ancestors: ::prost::alloc::vec::Vec<MintAncestor>,
}
/// MintAncestor pairs one historical BFA mint transition with the EVM deposit
/// that backed it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MintAncestor {
    /// 32-byte RGB OpId of the TS_BRIDGE transition.
    #[prost(bytes="vec", tag="1")]
    pub op_id: ::prost::alloc::vec::Vec<u8>,
    /// 32-byte EVM transaction hash of its FundsIn deposit.
    #[prost(bytes="vec", tag="2")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
}
/// CcdSource is the validated Concordium source of a fundsIn operation (the
/// finalized user->governance transfer or governance burn). The listener has
/// already validated finality and structure; the enclave trusts it and only
/// cross-checks the release amount (SignRequest.amount) against the destination.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CcdSource {
    /// Concordium source transaction hash (32 bytes).
    #[prost(bytes="vec", tag="1")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    /// Commission reported by the source operation.
    #[prost(uint64, tag="2")]
    pub commission: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EvmDestination {
    /// Raw ABI-encoded EVM function call.
    #[prost(bytes="vec", tag="1")]
    pub call_data: ::prost::alloc::vec::Vec<u8>,
    /// Sequential MultisigProxy nonce.
    #[prost(uint64, tag="2")]
    pub nonce: u64,
    /// Unix timestamp after which the signature is invalid.
    #[prost(uint64, tag="3")]
    pub deadline: u64,
    /// EVM chain ID used by the EIP-712 domain.
    #[prost(uint64, tag="4")]
    pub chain_id: u64,
    /// 20-byte EIP-712 verifying contract address.
    #[prost(bytes="vec", tag="5")]
    pub proxy_contract: ::prost::alloc::vec::Vec<u8>,
    /// Amount pre-extracted from call_data.
    #[prost(uint64, tag="6")]
    pub calldata_amount: u64,
    /// Commission pre-extracted from call_data.
    #[prost(uint64, tag="7")]
    pub calldata_commission: u64,
    /// lz_release, if set, signals that this is an lzFundsOutCall release and
    /// carries the LZ-specific fields for TeeLzFundsOut digest derivation and
    /// crosscheck. Absent for direct fundsOutCall releases.
    #[prost(message, optional, tag="8")]
    pub lz_release: ::core::option::Option<LzReleaseParams>,
}
/// LzReleaseParams carries the LayerZero-specific crosscheck fields for an
/// lzFundsOutCall release. Absent means a direct fundsOutCall release.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LzReleaseParams {
    /// dst_eid is the LayerZero endpoint ID of the destination chain
    /// (e.g. ETH mainnet = 30101, ETH Sepolia = 40161).
    #[prost(uint32, tag="1")]
    pub dst_eid: u32,
    /// min_amount_ld is the minimum acceptable amount after LZ slippage.
    #[prost(uint64, tag="2")]
    pub min_amount_ld: u64,
    /// recipient is the 32-byte padded destination address on the target chain.
    #[prost(bytes="vec", tag="3")]
    pub recipient: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RgbDestination {
    /// Destination operation index.
    #[prost(uint64, tag="1")]
    pub operation_idx: u64,
    /// Serialized PSBT to sign.
    #[prost(bytes="vec", tag="2")]
    pub psbt_bytes: ::prost::alloc::vec::Vec<u8>,
    /// Total non-change output amount.
    #[prost(uint64, tag="3")]
    pub psbt_output_amount: u64,
    /// RGB asset identifier associated with the transfer.
    #[prost(string, tag="4")]
    pub asset_id: ::prost::alloc::string::String,
    /// Raw destination RGB consignment bytes.
    #[prost(bytes="vec", tag="5")]
    pub consignment: ::prost::alloc::vec::Vec<u8>,
    /// keccak256(consignment).
    #[prost(bytes="vec", tag="6")]
    pub consignment_hash: ::prost::alloc::vec::Vec<u8>,
    /// The EVM deposit behind every earlier mint this consignment descends from.
    /// The terminal mint is bound to EvmSource.tx_hash instead, so listing it here
    /// is refused: that is the only way a spent lock could be substituted for the
    /// one this request pays with. Hints, never evidence - each is verified.
    #[prost(message, repeated, tag="7")]
    pub mint_ancestors: ::prost::alloc::vec::Vec<MintAncestor>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MerkleProofEntry {
    /// 32-byte transaction ID in display byte order.
    #[prost(bytes="vec", tag="1")]
    pub txid: ::prost::alloc::vec::Vec<u8>,
    /// Height of the block containing the transaction.
    #[prost(uint32, tag="2")]
    pub block_height: u32,
    /// Transaction position in the block.
    #[prost(uint32, tag="3")]
    pub tx_position: u32,
    /// 32-byte sibling hashes from leaf to Merkle root.
    #[prost(bytes="vec", repeated, tag="4")]
    pub merkle_path: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EvmSignatureResponse {
    /// 65-byte Ethereum signature: r || s || v.
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// The exact fundsOut calldata the signature commits to. For the RGB->EVM
    /// fundsOut path the enclave derives the OpId-bound fields (burnId,
    /// settlementData/fundsInIds) from the validated consignment and rewrites
    /// them, so this MAY differ from the call_data sent in EvmDestination. The
    /// caller MUST submit these bytes on-chain (the EIP-712 digest is keccak256
    /// over this calldata). Equal to the request's call_data on non-fundsOut /
    /// non-rgb-validation paths.
    #[prost(bytes="vec", tag="2")]
    pub call_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignedPsbtResponse {
    /// Serialized PSBT with enclave partial signatures.
    #[prost(bytes="vec", tag="1")]
    pub signed_psbt: ::prost::alloc::vec::Vec<u8>,
    /// Number of inputs signed by the enclave.
    #[prost(uint32, tag="2")]
    pub inputs_signed: u32,
}
/// Plain-BTC PSBT signing (create_utxo / plain withdrawals). Distinct from the
/// bridge/RGB-send path (SignRequest): carries NO RGB consignment and NO EVM
/// correlation. The enclave authorises it ONLY against an operator-pinned output
/// allowlist + amount cap (env BTC_ALLOWED_SCRIPTS / BTC_MAX_TOTAL_SATS), never a
/// listener-supplied flag, and signs on the vanilla BIP-86 account so it can
/// never co-sign a colored (RGB-allocated) input. A production (rgb-validation)
/// build refuses to sign when the allowlist/cap are unconfigured (fail-closed).
/// Response is a SignedPsbtResponse, same as the RGB-send path. Audit M-01 / #69.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignBtcRequest {
    /// Raw PSBT to sign (plain BTC; no consignment).
    #[prost(bytes="vec", tag="1")]
    pub psbt_bytes: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignRawMessageRequest {
    /// Arbitrary message wrapped and hashed using EIP-191 before signing.
    #[prost(bytes="vec", tag="1")]
    pub message: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RawSignatureResponse {
    /// 65-byte Ethereum signature: r || s || v.
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignRawDigestRequest {
    /// Optional; if set must equal keccak256(unsigned_tx). Dev-mode legacy path signs it directly.
    #[prost(bytes="vec", tag="1")]
    pub digest: ::prost::alloc::vec::Vec<u8>,
    /// Unsigned gas-tx preimage (EIP-1559 / legacy EIP-155). Required in release builds for shape/allowlist gating (audit TEE-XC-09 / #68).
    #[prost(bytes="vec", tag="2")]
    pub unsigned_tx: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RawDigestSignatureResponse {
    /// 65-byte signature produced by the gas transaction key.
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
/// SignCcdRequest asks the enclave to Ed25519-sign a Concordium account-transaction
/// hash with the governance key. The listener has already re-derived the hash and
/// verified the transaction structure/amounts; the enclave signs the hash directly.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignCcdRequest {
    /// Exactly 32 bytes, signed without additional hashing.
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CcdSignatureResponse {
    /// 64-byte Concordium Ed25519 signature.
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// 32-byte Ed25519 public key that produced `signature`. Ed25519 signatures are
    /// not recoverable, so the consumer cannot derive the signer the way it does on
    /// EVM; it needs the key to look the signature's credential and key index up in
    /// the governance account. Derived in the same operation as the signature, so
    /// the two cannot disagree.
    #[prost(bytes="vec", tag="2")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProxyFederationRequest {
    /// 32-byte hash passed to the federation signer.
    #[prost(bytes="vec", tag="1")]
    pub message_hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FederationSignatureResponse {
    /// 65-byte federation ECDSA signature.
    #[prost(bytes="vec", tag="1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InitiateCloningRequest {
    /// Pre-shared operator secret, never sent to the donor.
    #[prost(string, tag="1")]
    pub cloning_secret: ::prost::alloc::string::String,
    /// 20-byte EVM address of the intended donor.
    #[prost(bytes="vec", tag="2")]
    pub cluster_public_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InitiateCloningResponse {
    /// NSM document binding the encryption key and digest.
    #[prost(bytes="vec", tag="1")]
    pub requester_attestation: ::prost::alloc::vec::Vec<u8>,
    /// 32-byte requester X25519 public key.
    #[prost(bytes="vec", tag="2")]
    pub encryption_pubkey: ::prost::alloc::vec::Vec<u8>,
    /// 32-byte HMAC-SHA256 over the encryption public key.
    #[prost(bytes="vec", tag="3")]
    pub cloning_digest: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCloneRequest {
    /// 20-byte EVM address that must match the donor.
    #[prost(bytes="vec", tag="1")]
    pub cluster_public_key: ::prost::alloc::vec::Vec<u8>,
    /// 32-byte digest verified with the cloning secret.
    #[prost(bytes="vec", tag="2")]
    pub cloning_digest: ::prost::alloc::vec::Vec<u8>,
    /// 32-byte requester X25519 public key.
    #[prost(bytes="vec", tag="3")]
    pub encryption_pubkey: ::prost::alloc::vec::Vec<u8>,
    /// NSM document binding requester key and digest.
    #[prost(bytes="vec", tag="4")]
    pub requester_attestation: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCloneResponse {
    /// Seed encrypted using X25519, HKDF, and ChaCha20Poly1305.
    #[prost(bytes="vec", tag="1")]
    pub encrypted_seed: ::prost::alloc::vec::Vec<u8>,
    /// 32-byte donor ephemeral X25519 public key.
    #[prost(bytes="vec", tag="2")]
    pub donor_pubkey: ::prost::alloc::vec::Vec<u8>,
    /// NSM document binding the donor public key.
    #[prost(bytes="vec", tag="3")]
    pub donor_attestation: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetCloneRequest {
    /// Encrypted 64-byte seed returned by the donor.
    #[prost(bytes="vec", tag="1")]
    pub encrypted_seed: ::prost::alloc::vec::Vec<u8>,
    /// 32-byte donor ephemeral X25519 public key.
    #[prost(bytes="vec", tag="2")]
    pub donor_pubkey: ::prost::alloc::vec::Vec<u8>,
    /// NSM document binding the donor public key.
    #[prost(bytes="vec", tag="3")]
    pub donor_attestation: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetCloneResponse {
}
// Bitcoin header synchronization for in-enclave SPV validation.

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitHeadersRequest {
    /// Raw 80-byte Bitcoin headers (batch, contiguous, in ascending height order).
    /// Listener typically batches up to ~500 to keep gRPC messages small.
    #[prost(bytes="vec", repeated, tag="1")]
    pub headers: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Block height of headers\[0\]. Headers must connect to the enclave's stored
    /// chain (i.e. start_height == last_saved_height + 1) — except for the very
    /// first batch which connects to the compiled-in checkpoint.
    #[prost(uint32, tag="2")]
    pub start_height: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitHeadersResponse {
    /// enclave's tip after applying this batch
    #[prost(uint32, tag="1")]
    pub last_block_height: u32,
    /// 32 bytes
    #[prost(bytes="vec", tag="2")]
    pub last_block_hash: ::prost::alloc::vec::Vec<u8>,
    /// number of headers from the batch that validated
    #[prost(uint32, tag="3")]
    pub headers_accepted: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLastSavedBlockRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLastSavedBlockResponse {
    /// Height of the latest accepted header.
    #[prost(uint32, tag="1")]
    pub block_height: u32,
    /// 32-byte hash of the latest accepted header.
    #[prost(bytes="vec", tag="2")]
    pub block_hash: ::prost::alloc::vec::Vec<u8>,
}
// Readiness probe used by deploy orchestration to replace a fixed sleep between
// sequential enclave restarts. Internal only: never expose outside the host.

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthResponse {
    /// key_loaded && spv_synced. The only field a caller needs; the rest are
    /// diagnostics for logs.
    #[prost(bool, tag="1")]
    pub ready: bool,
    /// Signing key present, i.e. the phase state machine reached "active".
    #[prost(bool, tag="2")]
    pub key_loaded: bool,
    /// Header chain tip is recent enough that a signature would pass the same
    /// staleness gate signing applies. False while the chain is still catching up.
    #[prost(bool, tag="3")]
    pub spv_synced: bool,
    /// Phase name: "initial", "cloning", or "active".
    #[prost(string, tag="4")]
    pub phase: ::prost::alloc::string::String,
    /// Height of the latest accepted header (the compiled-in checkpoint height
    /// when no headers have been accepted yet).
    #[prost(uint32, tag="5")]
    pub spv_tip_height: u32,
    /// Block timestamp of that header.
    #[prost(uint32, tag="6")]
    pub spv_tip_time: u32,
    /// Enclave wall clock minus spv_tip_time, clamped at 0. Shows how far behind
    /// the chain still is.
    #[prost(uint32, tag="7")]
    pub spv_tip_age_secs: u32,
    /// Max age spv_tip_age_secs is compared against.
    #[prost(uint32, tag="8")]
    pub spv_max_tip_age_secs: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ErrorResponse {
    /// Stable enclave error category.
    #[prost(uint32, tag="1")]
    pub code: u32,
    /// Human-readable error description.
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
